//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGTestApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[{""ServerName"" : ""Server1"", ""DatabaseHost"" : ""192.168.4.122"", ""DatabasePort"" : 5432, ""DatabaseName"" : ""nprog"", ""UserId"" : ""krn"", ""Password"" : ""krn""}, {""ServerName"" : ""Server2"", ""DatabaseHost"" : ""192.168.4.239"", ""DatabasePort"" : 5432, ""DatabaseName"" : ""nprog"", ""UserId"" : ""krn"", ""Password"" : ""krn1015""}]")]
        public string ConnectionStrings {
            get {
                return ((string)(this["ConnectionStrings"]));
            }
            set {
                this["ConnectionStrings"] = value;
            }
        }
    }
}
