//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGTestApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[{""ServerName"" : ""Server1"", ""DatabaseHost"" : ""192.168.4.122"", ""DatabasePort"" : 5432, ""DatabaseName"" : ""nprog"", ""UserId"" : ""krn"", ""Password"" : ""krn"", ""ServerSize"" : ""1000""}, {""ServerName"" : ""Server2"", ""DatabaseHost"" : ""192.168.4.239"", ""DatabasePort"" : 5432, ""DatabaseName"" : ""nprog"", ""UserId"" : ""krn"", ""Password"" : ""krn1015"", ""ServerSize"" : ""1000""}]")]
        public string ConnectionStrings {
            get {
                return ((string)(this["ConnectionStrings"]));
            }
            set {
                this["ConnectionStrings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1KewdQFRR898O743PqMfOZTcpWouQT6kZVM0oGEvirlo")]
        public string SpreadSheetId {
            get {
                return ((string)(this["SpreadSheetId"]));
            }
            set {
                this["SpreadSheetId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("770463699938-rgsg4017hgpkru4tl26bc7v7di5p2375.apps.googleusercontent.com")]
        public string ClientId {
            get {
                return ((string)(this["ClientId"]));
            }
            set {
                this["ClientId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4ty1y5nMBcs5SaSDNJAVWFGk")]
        public string ClientSecret {
            get {
                return ((string)(this["ClientSecret"]));
            }
            set {
                this["ClientSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TimeoutInSeconds {
            get {
                return ((int)(this["TimeoutInSeconds"]));
            }
            set {
                this["TimeoutInSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BGTest")]
        public string SpreadSheetName {
            get {
                return ((string)(this["SpreadSheetName"]));
            }
            set {
                this["SpreadSheetName"] = value;
            }
        }
    }
}
